### ISSUE TITLE
Makefile:467: recipe for target 'all-recursive' failed

### ISSUE THREAD

**Issue by velenchan** [gilvillard/hplll#1]
Hi Gilles,

I just tried to install hplll on my computer, but failed with the following error message after "make"

Making all in tests
make[2]: Entering directory '/home/chen/Downloads/hplll-master/tests'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/chen/Downloads/hplll-master/tests'
Making all in macros
make[2]: Entering directory '/home/chen/Downloads/hplll-master/macros'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/chen/Downloads/hplll-master/macros'
Making all in examples
make[2]: Entering directory '/home/chen/Downloads/hplll-master/examples'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/chen/Downloads/hplll-master/examples'
Making all in drafts
make[2]: Entering directory '/home/chen/Downloads/hplll-master/drafts'
.deps/main.Po:1: *** missing separator.  Stop.
make[2]: Leaving directory '/home/chen/Downloads/hplll-master/drafts'
Makefile:467: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/chen/Downloads/hplll-master'
Makefile:375: recipe for target 'all' failed
make: *** [all] Error 2

Here are some more info:
1. 16.04.1-Ubuntu
2. gcc version 5.4.0 
3. directly run the following three steps
     ./autogen.sh
     ./configure
     make

Do you have any suggestions?

**Comment by gilvillard** [comment]
Hi,

gmp, mpfr, and fplll are correctly installed on the machine ? I'd have to see the config.log for instead. 

We can rather do this by mail directly.
